#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep  4 21:06:10 2020

@author: rebeccahwang
"""

import nazca as nd
import numpy as np
from dphox.design.aim import AIMNazca
from dphox.design.component import get_cubic_taper
from datetime import date

#chip = AIMNazca(
#    passive_filepath='/Users/rebeccahwang/research/aimfunrun/APSUNY_v35a_passive.gds',
#    waveguides_filepath='/Users/rebeccahwang/research/aimfunrun/APSUNY_v35_waveguides.gds',
#    active_filepath='/Users/rebeccahwang/research/aimfunrun/APSUNY_v35a_active.gds'
#)



dc_radius = 15
pdk_dc_radius = 25
sep = 30
gnd_length = 15

# testing params
test_interport_w = 50
test_gap_w = 0.3
test_bend_dim = get_bend_dim_from_interport_w(test_interport_w, test_gap_w)
test_tdc_interport_w = 50
test_tdc_interaction_l = 100
pull_in_phaseshift_l = 50
#test_tdc_bend_dim = get_bend_dim_from_interport_w(test_tdc_interport_w, test_gap_w)

mesh_interport_w = 50
mesh_phaseshift_l = 100
detector_loopback_params = (5, 20)

# Basic components

dc = chip.custom_dc(bend_dim=(dc_radius, test_bend_dim))[0]
mesh_dc = chip.pdk_dc(radius=pdk_dc_radius, interport_w=mesh_interport_w)
tap = chip.bidirectional_tap(10, mesh_bend=True)
#pull_apart_anchor = chip.nems_anchor()
#pull_in_anchor = chip.nems_anchor(connector_dim=(40, 5), fin_spring_dim=(50, 0.15),
#                                  pos_electrode_dim=None, neg_electrode_dim=None)
tdc_anchor = chip.nems_anchor(connector_dim=(test_tdc_interaction_l, 5),
                              pos_electrode_dim=None, neg_electrode_dim=None)
tdc = chip.nems_tdc(anchor=tdc_anchor)

tdc.put(0,0)
nd.export_gds(filename='tdctest.gds')